colorscheme thinkpad

syntax on

set relativenumber
set number
set hlsearch			    " Highlight all search results
set smartcase			    " Enable smart-case search
set ignorecase			    " Always case-insensitive
set incsearch			    " Searches for strings incrementally
 
set autoindent			    " Auto-indent new lines
set shiftwidth=4		    " Number of auto-indent spaces
set smartindent			    " Enable smart-indent
set smarttab			    " Enable smart-tabs
set softtabstop=4		    " Number of spaces per Tab
 
"" Advanced
set undolevels=1000		    " Number of undo levels
